#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}-{branch}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  COVERALLS_REPO_TOKEN:
    secure: Pn67B/ELnBY8YWJUBE4s4oIx98wS5NRLTOrP7AP/EiuU2l9brndSCF2cPL6+JUBe

#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration: Release

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore
- GitVersion /output buildserver /updateAssemblyInfo SolutionInfo.cs

build:
  project: NodaMoney.sln
  publish_nuget: true  # package projects with .nuspec files and push to artifacts
  verbosity: minimal

after_build:
- copy NodaMoney\bin\Release\NodaMoney.dll
- copy NodaMoney\bin\Release\NodaMoney.pdb
- copy NodaMoney\bin\Release\NodaMoney.xml
- 7z a -tzip NodaMoney.zip README.md LICENSE.txt NodaMoney.dll NodaMoney.pdb NodaMoney.xml

test_script:
- ps: >-
    iex ((Resolve-Path "packages\OpenCover.*\OpenCover.Console.exe").ToString() + ' --% -register:user -filter:"+[NodaMoney*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:NodaMoney.UnitTests/bin/Release/NodaMoney.UnitTests.dll" -output:coverage.xml')

    iex ((Resolve-Path "packages\coveralls.io.*\tools\coveralls.net.exe").ToString() + ' --opencover coverage.xml')


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
- path: NodaMoney.zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: y4qyCzCMLVH/DEwqh0WpXYryveAR7kuSSe25yd3PlLJms3dw7rB2gJpYc7HKW37y
  artifact: NodaMoney.zip
  draft: true
  on:
    branch: /^(\d+\.)?(\d+\.)?(\*|\d+)$/

- provider: NuGet
  server: https://www.nuget.org/
  api_key:
    secure: cJV4lINlVi8J4NOZBAS5GnaaugKWWO0Zi5jCSKfkDOgs5mEpPDjIf9K0D8hB4bTU
  skip_symbols: true
  on:
    branch: /^(\d+\.)?(\d+\.)?(\*|\d+)$/

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
- provider: Email
  to:
  - main@nodamoney.flowdock.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Slack
  auth_token:
    secure: jhC+/1OwjVll6PTQLyyYTxb0oouvf83oOYxp40ZLnMrmNhU9Las0wwIQY64+JJIa
  channel: general
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true