#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}-{branch}'
os: Visual Studio 2015
branches:
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  COVERALLS_REPO_TOKEN:
    secure: Pn67B/ELnBY8YWJUBE4s4oIx98wS5NRLTOrP7AP/EiuU2l9brndSCF2cPL6+JUBe
  NUGET_API_KEY:
    secure: cJV4lINlVi8J4NOZBAS5GnaaugKWWO0Zi5jCSKfkDOgs5mEpPDjIf9K0D8hB4bTU

#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration: Release

nuget:
  disable_publish_on_pr: true
 
build_script:
  - build.cmd DefaultAndCoveralls
 
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
- path: .\Artifacts\*.nupkg
  name: nuget
- path: .\Artifacts\*.zip
  name: zip


#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: y4qyCzCMLVH/DEwqh0WpXYryveAR7kuSSe25yd3PlLJms3dw7rB2gJpYc7HKW37y
  artifact: nuget, zip
  draft: true
  on:
    branch: /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    appveyor_repo_tag: true

- provider: NuGet
  server: https://www.nuget.org/
  api_key:
    secure: cJV4lINlVi8J4NOZBAS5GnaaugKWWO0Zi5jCSKfkDOgs5mEpPDjIf9K0D8hB4bTU
  skip_symbols: true
  on:
    appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
- provider: Slack
  incoming_webhook:
    secure: HzeM1/SGr4DgedFcdh1D17XdOCLKRG81irFVeMPTC5rg7O/WRFm0xEIJgOs92wb7UrOqQIe4dWujPHAVC8mCcmMPZ/U4dYDwvCUC6Jkltxc=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true