#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}-{branch}'
image: Visual Studio 2017
branches:
  except:
    - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  COVERALLS_REPO_TOKEN:
    secure: Pn67B/ELnBY8YWJUBE4s4oIx98wS5NRLTOrP7AP/EiuU2l9brndSCF2cPL6+JUBe
  NUGET_API_KEY:
    secure: cJV4lINlVi8J4NOZBAS5GnaaugKWWO0Zi5jCSKfkDOgs5mEpPDjIf9K0D8hB4bTU

#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration: Release

nuget:
  disable_publish_on_pr: true
 
build_script:
  - ps: .\build.ps1 -target AppVeyor
 
test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: y4qyCzCMLVH/DEwqh0WpXYryveAR7kuSSe25yd3PlLJms3dw7rB2gJpYc7HKW37y
  artifact: nuget
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications: